-- Immutable operational timeline for each booking, visible only to administrators.

create table if not exists public.booking_events (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  event_type text not null,
  actor_type text not null default 'system',
  resulting_status text,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.booking_events
  drop constraint if exists booking_events_actor_type_check;

alter table public.booking_events
  add constraint booking_events_actor_type_check
  check (actor_type in ('patient', 'admin', 'system'))
  not valid;

alter table public.booking_events
  validate constraint booking_events_actor_type_check;

create index if not exists booking_events_booking_created_idx
  on public.booking_events (booking_id, created_at desc);

alter table public.booking_events enable row level security;

drop policy if exists booking_events_admin_all on public.booking_events;

create policy booking_events_admin_all
  on public.booking_events
  for all
  to authenticated
  using (public.is_admin_user())
  with check (public.is_admin_user());

insert into public.booking_events (
  booking_id,
  event_type,
  actor_type,
  resulting_status,
  description,
  metadata,
  created_at
)
select
  bookings.id,
  'imported',
  'system',
  bookings.status,
  'Reserva incorporada al historial operativo.',
  jsonb_build_object(
    'booking_date', bookings.booking_date,
    'booking_time', bookings.booking_time
  ),
  coalesce(bookings.created_at, now())
from public.bookings
where not exists (
  select 1
  from public.booking_events
  where public.booking_events.booking_id = bookings.id
);
